function result = is_box_b_within_box_a(box_a, box_b)
  result = ( box_b(1,1) >= box_a(1,1) ) && ...
           ( box_b(1,2) <= box_a(1,2) ) && ...
           ( box_b(2,1) >= box_a(2,1) ) && ...
           ( box_b(2,2) <= box_a(2,2) ) ;
end