avi_file_name = 'movie-enhanced.avi' ;
ufmf_file_name = 'movie-enhanced-test.ufmf' ;
output_frame_count = 600 ;
avi2ufmf(avi_file_name, ...
         'ufmfname', ufmf_file_name, ...
         'startframe', 1, ...
         'endframe', output_frame_count, ...
         'verbose', 3, ...
         'diffmode', 'other', ...
         'blocknframes',200,...
         'bgnframes',50,...
         'bgthresh', 8) ;

% Try to read it
header = ufmf_read_header(ufmf_file_name) ;
output_frame_count = header.nframes ; 
read_frame = ufmf_get_readframe_fcn(header) ;
for i = 1 : output_frame_count ,
    frame = read_frame(i) ;
end
